language: python
services:
  - postgresql
addons:
  postgresql: "9.3"
python:
  - 3.6
before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - sudo apt-get update
  - sudo apt-get install language-pack-fa
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
install: pip install -e .
script: coverage run --source microhttp_restful $(which nosetests)
after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry coveralls; fi
